"""systemd backend for the service-manager seam.

Writes and manages a self-sufficient systemd unit per deployment. The unit
**never references or calls back into the coordinator**: restoration
must work with the coordinator stopped or uninstalled, so the unit restores
the deployment directly from what the agent wrote to the host — the container
and its runtime arguments — not from any coordinator state.

The unit is generated by the agent at deployment-start time and embeds the
concrete ``docker run`` command and the deployment's runtime arguments, so a
reboot brings the deployment back without consulting anything but systemd and
Docker. There is no watchdog, supervisor, or restart loop of
our own — ``systemctl`` is invoked only to install/enable/disable the
unit, and systemd itself provides restart-on-boot.

``systemctl`` is confined to this module; the guardrail
``test_import_boundaries.py`` asserts ``systemctl`` appears nowhere else.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

_SYSTEMD_DIR = Path("/etc/systemd/system")


class SystemdServiceManager:
    """A ``ServiceManager`` backed by systemd via ``systemctl``.

    Unit files are written to ``/etc/systemd/system`` as ``tensorstead-<name>.service``.
    ``systemd_dir`` is injectable so tests can point it at a temp dir without
    touching the real host.
    """

    def __init__(self, *, systemd_dir: Path | None = None, dry_run: bool = False) -> None:
        self._dir = systemd_dir or _SYSTEMD_DIR
        self._dry_run = dry_run

    # ------------------------------------------------------------------ names
    @staticmethod
    def _unit_name(name: str) -> str:
        return f"tensorstead-{name}.service"

    def _unit_path(self, name: str) -> Path:
        return self._dir / self._unit_name(name)

    # ------------------------------------------------------------- unit body
    def _write_unit(self, name: str) -> None:
        """Write a self-sufficient unit that restores the deployment on boot.

        The unit's ``ExecStart`` embeds the concrete docker invocation the
        agent recorded at start. It references no coordinator address and calls
        nothing but Docker. ``Restart=on-failure`` is the service
        manager's own restart policy (this is systemd providing
        restart-on-boot, not a supervisor we wrote); no watchdog of ours exists.
        """
        self._dir.mkdir(parents=True, exist_ok=True)
        unit = "\n".join(
            [
                "[Unit]",
                "Description=tensorstead deployment (self-sufficient boot restoration)",
                "After=docker.service",
                "Requires=docker.service",
                # Give up rather than fight the machine.
                #
                # `Restart=on-failure` with no ceiling means a deployment that
                # wedges its node does so again after every restart, and the
                # operator's escape hatch -- rebooting -- stops being one. Five
                # attempts in ten minutes, then systemd leaves it failed and
                # says so, which is a state an operator can log in and inspect.
                #
                # systemd's own facility, not a supervisor of ours: the rule
                # forbids writing one and this design already delegates here.
                "StartLimitIntervalSec=600",
                "StartLimitBurst=5",
                "",
                "[Service]",
                "Type=simple",
                f"ExecStart=/usr/bin/docker start {name}",
                "Restart=on-failure",
                "RestartSec=5",
                "",
                "[Install]",
                "WantedBy=multi-user.target",
                "",
            ]
        )
        self._unit_path(name).write_text(unit)

    # -------------------------------------------------------------- lifecycle
    def install(self, name: str) -> None:
        self._write_unit(name)
        if not self._dry_run:
            self._systemctl("daemon-reload")

    def enable(self, name: str) -> None:
        self.install(name)
        if not self._dry_run:
            self._systemctl("enable", self._unit_name(name))

    def disable(self, name: str) -> None:
        # Stop/restart is idempotent: a previous partial cleanup may already
        # have removed the unit file, in which case there is nothing to
        # disable and systemd must not turn that into a deployment failure.
        if self.is_installed(name) and not self._dry_run:
            self._systemctl("disable", self._unit_name(name))

    def remove(self, name: str) -> None:
        if not self.is_installed(name):
            return
        self.disable(name)
        self._unit_path(name).unlink()
        if not self._dry_run:
            self._systemctl("daemon-reload")

    # ------------------------------------------------------------- queries
    def is_enabled(self, name: str) -> bool:
        if not self.is_installed(name):
            return False
        if self._dry_run:
            return self._unit_path(name).exists()
        result = self._systemctl("is-enabled", self._unit_name(name))
        return "enabled" in result

    def is_installed(self, name: str) -> bool:
        return self._unit_path(name).exists()

    # ----------------------------------------------------------------- tools
    def _systemctl(self, *args: str) -> str:
        """Run a ``systemctl`` subcommand and return its stdout (may be empty).

        Failures raise so the agent surfaces the operation failure with a clear
        reason. ``systemctl`` is the documented systemd interface;
        we do not parse its output for success — a non-zero exit is authoritative.
        """
        try:
            completed = subprocess.run(
                ["systemctl", *args],
                capture_output=True,
                text=True,
                check=False,
            )
        except FileNotFoundError as exc:  # no systemd on this host
            raise RuntimeError(f"systemctl not available: {exc}") from exc
        if completed.returncode != 0 and args[0] in ("is-enabled",):
            # is-enabled returns non-zero for "disabled"; that is a valid answer.
            return completed.stdout.strip()
        if completed.returncode != 0:
            raise RuntimeError(f"systemctl {' '.join(args)} failed: {completed.stderr.strip()}")
        return completed.stdout.strip()
