"""Repository port (persistence seam).

A narrow, persistence-agnostic interface for the coordinator's declared state.
The SQLite adapter implements it; nothing outside the adapter
touches SQL or a connection object. The boundary is separation of concerns, not
a generic database abstraction — it implies no PostgreSQL compatibility goal in
v1.
"""

from __future__ import annotations

from datetime import datetime
from typing import Protocol

from tensorstead.domain.approvals import CodeExecutionApproval
from tensorstead.domain.models import (
    Credential,
    Deployment,
    DeploymentRevision,
    ImageBuildSpec,
    ImageRecord,
    InferenceCredential,
    Model,
    ModelReplica,
    ModelSource,
    Node,
    Operation,
)


class Repository(Protocol):
    """Persist and query declared state.

    Every method is a unit of explicit transaction management at the caller's
    choice: the adapter exposes the transaction boundary and the
    caller decides whether a multi-write operation commits atomically.
    """

    # --- Nodes ---
    def save_node(self, node: Node) -> None: ...
    def get_node(self, node_id: str) -> Node | None: ...
    def get_node_by_name(self, name: str) -> Node | None: ...
    def list_nodes(self) -> list[Node]: ...
    def delete_node(self, node_id: str) -> None: ...

    # --- Model sources ---
    def save_model_source(self, source: ModelSource) -> None: ...
    def get_model_source(self, source_id: str) -> ModelSource | None: ...

    # --- Models & replicas ---
    def save_model(self, model: Model) -> None: ...
    def get_model(self, model_id: str) -> Model | None: ...
    def update_model_content(
        self,
        model_id: str,
        *,
        content_digest: str | None = None,
        size_bytes: int | None = None,
    ) -> None: ...
    def list_models(self) -> list[Model]: ...
    def find_model(
        self,
        source_id: str,
        source_model_id: str,
        resolved_revision: str | None,
        file_selector: tuple[str, ...] = (),
    ) -> Model | None: ...
    def save_replica(self, replica: ModelReplica) -> None: ...
    def list_replicas(self, model_id: str) -> list[ModelReplica]: ...
    def get_replica(self, model_id: str, node_id: str) -> ModelReplica | None: ...
    def delete_model(self, model_id: str) -> None: ...
    def delete_replica(self, model_id: str, node_id: str) -> None: ...
    def delete_model_and_replicas(self, model_id: str) -> None:
        """Delete a logical model row and all of its replicas in one transaction.

        The replica rows and the model row are committed together or not at
        all, so a failure partway through cannot leave the store in the
        half-deleted state where ``model_list`` reports ``replicas: []`` for a
        model row that is still present.
        """
        ...

    # --- Credentials ---
    def save_credential(self, credential: Credential) -> None: ...
    def list_credentials(self) -> list[Credential]: ...
    def get_credential(self, source_id: str, name: str) -> Credential | None: ...
    def delete_credential(self, source_id: str, name: str) -> None: ...

    # Inference credentials. Separate from model-source credentials
    # because they authenticate in the opposite direction: someone else to a
    # runtime, rather than this product to an upstream.
    def save_inference_credential(self, credential: InferenceCredential) -> None: ...

    def list_inference_credentials(self) -> list[InferenceCredential]: ...

    def get_inference_credential(self, name: str) -> InferenceCredential | None: ...

    def delete_inference_credential(self, name: str) -> None: ...

    def bind_inference_credential(self, deployment_id: str, name: str) -> None: ...

    def unbind_inference_credential(self, deployment_id: str) -> None: ...

    def get_bound_inference_credential(self, deployment_id: str) -> str | None: ...

    # Managed runtime images.
    def save_build_spec(self, spec: ImageBuildSpec) -> None: ...

    def list_build_specs(self) -> list[ImageBuildSpec]: ...

    def get_build_spec(self, name: str) -> ImageBuildSpec | None: ...

    def delete_build_spec(self, name: str) -> None: ...

    # ------------------------------------------- code-execution approvals
    def save_code_approval(self, approval: CodeExecutionApproval) -> None: ...

    def list_code_approvals(self) -> list[CodeExecutionApproval]: ...

    def get_code_approval(self, approval_id: str) -> CodeExecutionApproval | None: ...

    def find_code_approval(self, fingerprint: str) -> CodeExecutionApproval | None: ...

    def delete_code_approval(self, approval_id: str) -> None: ...

    # --- Deployments ---
    def save_deployment(self, deployment: Deployment) -> None: ...
    def get_deployment(self, deployment_id: str) -> Deployment | None: ...
    def list_deployments(self) -> list[Deployment]: ...
    def delete_deployment(self, deployment_id: str) -> None: ...

    # --- Deployment revisions (immutable; never updated) ---
    def insert_revision(self, revision: DeploymentRevision) -> None: ...
    def get_revision(self, deployment_id: str, revision: int) -> DeploymentRevision | None: ...
    def list_revisions(self, deployment_id: str) -> list[DeploymentRevision]: ...

    # --- Operations ---
    def save_operation(self, operation: Operation) -> None: ...
    def get_operation(self, operation_id: str) -> Operation | None: ...
    def list_operations(self, deployment_id: str | None = None) -> list[Operation]: ...
    def resolve_non_terminal_operations(self, *, finished_at: datetime) -> None: ...

    # --- Images ---
    def save_image(self, image: ImageRecord) -> None: ...
    def list_images(self) -> list[ImageRecord]: ...
    def delete_image(self, node_id: str, digest: str) -> None: ...
