#!/usr/bin/env python3
"""Build Tensorstead and write local, immutable provenance for the artifact.

The package release version identifies the software release.  Every invocation
also receives a monotonically increasing local build number and records the
wheel's SHA-256, source revision, dirty-tree status, and creation time.  The
ledger is deliberately local and ignored by Git: a build record describes an
artifact, not source code.

Each build also leaves an **independent, never-overwritten copy** of its
artifacts in ``dist/builds/<build_number>/``. The canonical wheel in ``dist/``
is refreshed to the latest build (the version-pinned deploy pointer), but the
prior build's wheel survives in its own directory — so a deploy that goes wrong
can be rolled back by pointing ``TENSORSTEAD_DEPLOY_ARTIFACT`` at a previous build
directory rather than rebuilding from source.
"""

from __future__ import annotations

import hashlib
import json
import shutil
import subprocess
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
DIST = ROOT / "dist"
LEDGER = ROOT / ".tensorstead" / "build-history.jsonl"


def _run_git(*args: str) -> str | None:
    result = subprocess.run(["git", *args], cwd=ROOT, check=False, capture_output=True, text=True)
    if result.returncode:
        return None
    return result.stdout.strip()


def _next_build_number() -> int:
    if not LEDGER.exists():
        return 1

    last_number = 0
    for line in LEDGER.read_text(encoding="utf-8").splitlines():
        if line.strip():
            last_number = max(last_number, int(json.loads(line)["build_number"]))
    return last_number + 1


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as artifact:
        for chunk in iter(lambda: artifact.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _sdist_for(wheel: Path) -> Path | None:
    """The sdist uv built alongside ``wheel`` (same version), if present."""
    version = wheel.name.split("-")[1]
    candidates = sorted(DIST.glob(f"tensorstead-{version}.tar.gz"))
    return candidates[-1] if candidates else None


def _archive_build(dist: Path, wheel: Path, sdist: Path | None, record: dict[str, Any]) -> Path:
    """Copy one build's artifacts into an immutable per-build directory.

    ``dist/builds/<build_number>/`` holds the wheel, the sdist, and the build
    manifest, indexed by the monotonically increasing ``build_number``. Because
    build numbers only ever increase, a later build never touches this
    directory — which is what makes a prior build's wheel recoverable for
    rollback. The directory must not already exist: the only way to collide is a
    deleted or hand-edited ledger while old build directories remain, and
    silently overwriting one would destroy exactly the history this exists to
    keep, so fail loudly instead.
    """
    build_dir = dist / "builds" / str(record["build_number"])
    if build_dir.exists():
        raise FileExistsError(
            f"build archive already exists: {build_dir}. Refusing to overwrite a "
            "prior build's artifacts. If the ledger was reset deliberately, remove "
            "stale directories under dist/builds/ first."
        )
    build_dir.mkdir(parents=True)
    shutil.copy2(wheel, build_dir / wheel.name)
    if sdist is not None:
        shutil.copy2(sdist, build_dir / sdist.name)
    manifest = build_dir / f"{wheel.name}.build.json"
    manifest.write_text(json.dumps(record, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return build_dir


# Written into the package immediately before the build and removed after, so
# the identity travels *inside* the wheel rather than in a sidecar beside it.
#
# The sidecar manifest answers "what did this build produce". It cannot answer
# "what is that node running", because it never leaves the controller -- and
# ``agent_version`` could not answer it either: it reports the package version,
# which has read 0.1.8 for sixty consecutive builds. So an operator had no way
# to distinguish a current appliance from one six deploys behind. That is this
# product's own release process reproducing the record-and-reality gap the
# product exists to close.
_PROVENANCE = ROOT / "src" / "tensorstead" / "_build.py"

_PROVENANCE_TEMPLATE = '''"""Build identity, generated by scripts/build_package.py. Not source.

Absent from a source checkout, and from any wheel not produced by that script.
The agent then reports its build as unknown -- which is true, and better than a
version string that has not moved in sixty builds.
"""

BUILD_NUMBER = {build_number!r}
GIT_REVISION = {git_revision!r}
BUILT_AT = {built_at!r}
SOURCE_TREE_DIRTY = {source_tree_dirty!r}
'''


def main() -> int:
    # Everything the identity needs is knowable before the build. Only the
    # wheel's own hash is not, and that stays in the sidecar.
    pre: dict[str, Any] = {
        "build_number": _next_build_number(),
        "built_at": datetime.now(UTC).isoformat(),
        "git_revision": _run_git("rev-parse", "HEAD"),
        "source_tree_dirty": bool(_run_git("status", "--porcelain")),
    }
    try:
        _PROVENANCE.write_text(_PROVENANCE_TEMPLATE.format(**pre), encoding="utf-8")
        subprocess.run(["uv", "build"], cwd=ROOT, check=True)
    finally:
        # Removed however the build ended. A generated file left behind would
        # make the next build report the previous build's identity -- a stale
        # record in exactly the costume this is meant to remove.
        _PROVENANCE.unlink(missing_ok=True)

    wheels = sorted(
        DIST.glob("tensorstead-*.whl"),
        key=lambda path: path.stat().st_mtime_ns,
    )
    if not wheels:
        raise RuntimeError("uv build completed but did not produce a Tensorstead wheel")

    wheel = wheels[-1]
    sdist = _sdist_for(wheel)
    record: dict[str, Any] = {
        **pre,
        "package_version": _package_version(),
        "wheel": wheel.name,
        "sha256": _sha256(wheel),
    }

    LEDGER.parent.mkdir(mode=0o700, exist_ok=True)
    with LEDGER.open("a", encoding="utf-8") as history:
        history.write(json.dumps(record, sort_keys=True) + "\n")

    # The canonical sidecar in dist/ reports which build the deploy wheel is.
    manifest = wheel.with_suffix(wheel.suffix + ".build.json")
    manifest.write_text(json.dumps(record, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    # An independent, never-overwritten copy for rollback.
    build_dir = _archive_build(DIST, wheel, sdist, record)

    print(
        f"Built Tensorstead {record['package_version']} build {record['build_number']}: "
        f"{wheel.name}\nSHA-256: {record['sha256']}\n"
        f"Manifest: {manifest}\nArchived: {build_dir}"
    )
    return 0


def _package_version() -> str:
    pyproject = ROOT / "pyproject.toml"
    try:
        import tomllib
    except ModuleNotFoundError:  # pragma: no cover - Python >=3.12 is required
        import tomli as tomllib  # type: ignore[no-redef]
    return str(tomllib.loads(pyproject.read_text(encoding="utf-8"))["project"]["version"])


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except subprocess.CalledProcessError as exc:
        raise SystemExit(exc.returncode) from exc
